spring.application.name=backend
## DATABASE ###
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

