spring.application.name=backend
### JPA / HIBERNATE ###
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
### Configurer serveur ####

###server.port=8089
