name: CI-CD

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

jobs:

  backend-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run Tests
        run: mvn clean test

  frontend-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

  docker-build-push:
    needs:
      - backend-test
      - frontend-build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Backend Image
        run: |
          docker build \
          -t ghcr.io/${{ github.repository_owner }}/notes-backend:latest \
          ./backend

      - name: Build Frontend Image
        run: |
          docker build \
          -t ghcr.io/${{ github.repository_owner }}/notes-frontend:latest \
          ./frontend

      - name: Push Backend Image
        run: |
          docker push \
          ghcr.io/${{ github.repository_owner }}/notes-backend:latest

      - name: Push Frontend Image
        run: |
          docker push \
          ghcr.io/${{ github.repository_owner }}/notes-frontend:latest